spring:
  application:
    name: MovieAPI

  datasource:
    url: jdbc:postgresql://localhost:5432/moviedb
    username: movieuser
    password: 1619

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

project:
  poster: poster/